---
services:
  - docker

env:
  global:
    - ROLE_GLOBALS="postgresql_shared_buffers=32MB"
  matrix:
#    - ROLE_OPTIONS="postgresql_version=9.1" ANSIBLE_VERSION="1.9.4"
#    - ROLE_OPTIONS="postgresql_version=9.2" ANSIBLE_VERSION="1.9.4"
#    - ROLE_OPTIONS="postgresql_version=9.3" ANSIBLE_VERSION="1.9.4"
#    - ROLE_OPTIONS="postgresql_version=9.4" ANSIBLE_VERSION="1.9.4"
#    - ROLE_OPTIONS="postgresql_version=9.5" ANSIBLE_VERSION="1.9.4"
#    - ROLE_OPTIONS="postgresql_version=9.6" ANSIBLE_VERSION="1.9.4"
#    - ROLE_OPTIONS="postgresql_version=9.1" ANSIBLE_VERSION="2.1.2.0"
#    - ROLE_OPTIONS="postgresql_version=9.2" ANSIBLE_VERSION="2.1.2.0"
#    - ROLE_OPTIONS="postgresql_version=9.3" ANSIBLE_VERSION="2.1.2.0"
#    - ROLE_OPTIONS="postgresql_version=9.4" ANSIBLE_VERSION="2.1.2.0"
#    - ROLE_OPTIONS="postgresql_version=9.5" ANSIBLE_VERSION="2.1.2.0"
    - DISTRO="ubuntu1604" PLAYBOOK="test_9.6.yml" ANSIBLE_VERSION="2.2.0"
    - DISTRO="ubuntu1604" PLAYBOOK="test_9.6.yml" ANSIBLE_VERSION="latest"
    - DISTRO="ubuntu1604" PLAYBOOK="test_9.5.yml" ANSIBLE_VERSION="latest"
    - DISTRO="centos7" PLAYBOOK="test_9.6.yml" ANSIBLE_VERSION="2.2.0"
    - DISTRO="centos7" PLAYBOOK="test_9.6.yml" ANSIBLE_VERSION="latest"
    - DISTRO="centos7" PLAYBOOK="test_9.5.yml" ANSIBLE_VERSION="latest"

script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://raw.githubusercontent.com/briandbecker/ansible-role-test-shims/master/test.sh
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - env ansible_version=$ANSIBLE_VERSION playbook=$PLAYBOOK ${PWD}/tests/test.sh
